server.port: 8081

spring.application.name: gateway
spring.config.import: "configserver:"
app.config-server: localhost

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://${app.config-server}:8888
  application:
    name: user

---
spring.config.activate.on-profile: docker

app.config-server: config-server